import Head from 'next/head'
import styles from '../styles/Home.module.css'

const stardateCalculate = require('../public/StardateCalculate');

const stardateM = stardateCalculate.stardateMethods();

const submitTOSStardate = async (event) =>{
  event.preventDefault();
  var realDate = stardateM.calculaDateByStardate(event.target.stardate.value)
  var realdateString = realDate.getDate() + "-" + realDate.getMonth() + "-" + realDate.getFullYear()
  alert(`Data = ${realdateString}`);
}


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calculo de Data Estrelar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Calculo da data estrelar
        </h1>
        <h2>Data estrelar TOS</h2>
        <form className={styles.form} onSubmit={submitTOSStardate}>
          <label htmlFor='stardate'>Data Estrelar</label>
          <input id='stardate' name='stardate' type='number' step='0.1' required/>
          <button type='submit'>Calcule</button>
        </form>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
